use crate::IntoUcResult;
pub mod catalog;
pub mod schema;
pub mod table;
pub mod volume;
pub mod function;
pub mod model;
pub mod user;
pub mod credential;
pub mod external_location;
pub mod property;
pub mod staging;
pub mod delta;
pub mod metastore;

pub use catalog::CatalogRepo;
pub use schema::SchemaRepo;
pub use table::TableRepo;
pub use volume::VolumeRepo;
pub use function::FunctionRepo;
pub use model::ModelRepo;
pub use user::UserRepo;
pub use credential::CredentialRepo;
pub use external_location::ExternalLocationRepo;
pub use property::PropertyRepo;
pub use staging::StagingTableRepo;
pub use delta::DeltaCommitRepo;
pub use metastore::MetastoreRepo;
